version: 2.1
orbs:
  ruby: cimg/ruby@1.1.1
  buildevents: honeycombio/buildevents@0.5
  carwow: carwow/carwow-orb@0.4

jobs:
  build:
    environment: *environment
    executor: carwow/ruby
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install unixodbc-dev
      - run: sudo apt-get autoclean
      - run: sudo apt-get clean
      - run: gem install bundler
      - run: bundle install
      - run: rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
