version: 2.1
orbs:
  ruby: circleci/ruby@1.7.1

jobs:
  build:
    parameters:
      ruby:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby >>

    steps:
      - checkout
      - run: sudo apt-get install unixodbc-dev
      - run: gem install bundler
      - run: bundle install
      - run: rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby: ['2.6', '2.7', '3.0', '3.1']
