version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node

    steps:
      - checkout
      - run: sudo apt-get install unixodbc-dev
      - run: gem install bundler
      - run: bundle install
      - run: rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
