version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6-node

    steps:
      - run: echo  test
      - checkout
      - run: sudo apt-get update && sudo apt-get install unixodbc-dev && sudo apt-get clean
      - run: gem install bundler
      - run: bundle install
      - run: rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
